baseURL: "https://jessequinn.info/"
title: welcome to jessequinn.info
paginate: 5
theme: hugo-papermod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
    disableXML: true
    minifyOutput: true

copyright: '**[jessequin.info](https://jessequinn.info)**'

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: jessequinn.info
    description: "site of jesse quinn, developer and SRE, and just a good person"
    keywords: [Blog, Portfolio]
    author: Me
    # author: ["Me", "You"] # multiple authors
    images: ["<link or path of image for opengraph, twitter-cards>"]
    DateFormat: "January 2, 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: false
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "<link / abs url>"
        favicon16x16: "<link / abs url>"
        favicon32x32: "<link / abs url>"
        apple_touch_icon: "<link / abs url>"
        safari_pinned_tab: "<link / abs url>"

    label:
        text: "Home"
#        icon: /home-svgrepo-com.svg
#        iconHeight: 35

    # profile-mode
    profileMode:
        enabled: enabled # needs to be explicitly set
        title: Jesse Quinn
        subtitle: "site reliability engineer and software developer"
        imageUrl: "logo.svg"
        imageWidth: 120
        imageHeight: 120
        imageTitle: profile image
        buttons:
            - name: Archives
              url: archives
            - name: Posts
              url: posts
            - name: Tags
              url: tags

    # home-info mode
    homeInfoParams:
        Title: "Hi there \U0001F44B"
        Content: Welcome to my site

    socialIcons:
        - name: linkedin
          url: "https://www.linkedin.com/in/jessequinn/?lipi=urn%3Ali%3Apage%3Ad_flagship3_feed%3B77lH7a5hSA6cTRnls6TvzQ%3D%3D"
        - name: github
          url: "https://github.com/jessequinn"
        - name: email
          url: "mailto:me@jessequinn.info"

    analytics:
        google:
            SiteVerificationTag: "XYZabc"
        bing:
            SiteVerificationTag: "XYZabc"
        yandex:
            SiteVerificationTag: "XYZabc"

    cover:
        responsiveImages: true
        hidden: false # hide everywhere but not in structured data
        hiddenInList: false # hide on list pages and home
        hiddenInSingle: false # hide on single page

    editPost:
        URL: "https://github.com/jessequinn/hugo-personal-site/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: resume
          name: resume
          url: /resume/
          weight: 10
        - identifier: publications
          name: publications
          url: /publications/
          weight: 20

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
        - REDIR

outputFormats:
    REDIR:
        baseName: "redirects"
        isPlainText: true
        mediaType: "text/plain"
        notAlternative: true